# Generated by Django 4.0.2 on 2022-02-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='VaultMovement',
            fields=[
                ('abstractmovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movements.abstractmovement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='vaults.vault')),
            ],
            bases=('movements.abstractmovement',),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('abstractmovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movements.abstractmovement')),
                ('message', models.CharField(max_length=140)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('movements.abstractmovement',),
        ),
    ]
