# Generated by Django 4.0.1 on 2022-02-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='message',
        ),
    ]
