# Generated by Django 4.0.1 on 2022-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_remove_movement_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='message',
            field=models.CharField(default='Test', max_length=140),
            preserve_default=False,
        ),
    ]
