# Generated by Django 4.0.2 on 2022-02-15 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaults', '0001_initial'),
        ('movements', '0003_movement_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='movement_id',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='status',
        ),
        migrations.AddField(
            model_name='movement',
            name='abstractmovement_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movements.abstractmovement'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VaultMovement',
            fields=[
                ('abstractmovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movements.abstractmovement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='vaults.vault')),
            ],
            bases=('movements.abstractmovement',),
        ),
    ]
