# Generated by Django 4.0.2 on 2022-02-15 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('vault_id', models.AutoField(primary_key=True, serialize=False)),
                ('vault_name', models.CharField(max_length=100)),
                ('vault_desc', models.CharField(max_length=240, null=True)),
                ('vault_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vault_date', models.DateField(null=True)),
                ('vault_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
