# Generated by Django 4.0.2 on 2022-02-17 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_receiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
